name: CI/CD

on:
  pull_request:
    branches:
      - main

env:
  PYTHON_VERSION: 3.11.9 # Github runner does not support Python 3.11.10 for Macos yet

jobs:
  test:
    name: Test on ${{ matrix.os }} with ${{ matrix.arch }}
    runs-on: ${{ matrix.os }}

    strategy:
      matrix:
        include:
          - os: windows-latest
            arch: x64
          - os: windows-latest
            arch: arm64
      fail-fast: false

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python ${{ env.PYTHON_VERSION }} on ${{ matrix.arch }}
        uses: actions/setup-python@v5
        with:
          python-version: ${{ env.PYTHON_VERSION }}

      - name: Install dependencies using system package manager on Windows
        if: runner.os == 'Windows'
        run: choco install ffmpeg

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
      # Add bundling and deployment on merging to production branch
      - name: Build exe with PyInstaller
        if: runner.os == 'Windows'
        run: |
          pyinstaller --onefile Wisp.py
          # Adjust the command based on your project structure

      - name: Test exe file
        if: runner.os == 'Windows'
        run: |
          cd dist
          .\Wisp.exe
          # Add commands to verify the exe runs correctly

      - name: Run tests
        run: pytest


